### ISSUE TITLE
Convert attcehemnt to file tab is always giving setting options

### ISSUE THREAD

**Issue by rbhagat30** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#27]
I done with all the setting still clicking on the page i am not redrecting to the page where i should get the option please  help me to convert the att
![untitled](https://user-images.githubusercontent.com/29428190/27699988-d08ff7fc-5d19-11e7-90dc-4c44f5743948.png)
achemnet

**Comment by DouglasCAyers** [comment]
Hello @rbhagat30,

Thanks for trying out my conversion app and for sharing screen shot. Though, I'm not certain what issue you're needing help with?

What happens when you click those menu options: *Setup Conversion Settings*, *Test Conversion*, *Automate Conversion*?

Thanks,

Doug

**Comment by rbhagat30** [comment]
Hi Douglas ,


Thanks for prompt reply .when i click on Setup Conversion Settings, Test Conversion, Automate Conversion  setting window is open. after doing all the setting again same page is displaying


can you please share another way to reach attachment to file page .


Thanks

Rajni

________________________________

**Comment by rbhagat30** [comment]
Hi Douglas,

Thanks  for your precious time to giving into my issue

There is one problem with this app, actually while converting  attachment into file for each attachment it is creating  of attachment and file ,means it is creating duplicate attachments. For example we have 2 attachments in case record when we click on conversion it creating duplicate 2 attachments along with files so  total 4 attachments and 2 files.is there any way to change the setting somewhere either in conversion setting or somewhere to only create the file not the attachments.

Thanks
Rajni

**Comment by DouglasCAyers** [comment]
@rbhagat30, could you please share screen shot of where you're seeing duplicates?

Please note that the "Notes & Attachments" related list displays both Attachments and Files; so any records in the "Files" related list will be listed in the "Notes & Attachments" related list too, but is the same record, not a duplicate. You would see this if your conversion setting is set to not delete converted records.

**Comment by rbhagat30** [comment]
Hi Douglas,
 I have done all the setting  this is not working  still not working for me .
Please find the screenshot

[cid:image001.png@01D2F6AC.6C66CD10]

From: Bhagat, Rajni
Sent: Monday, July 03, 2017 11:30 AM
To: DouglasCAyers/sfdc-convert-attachments-to-chatter-files <reply@reply.github.com>; DouglasCAyers/sfdc-convert-attachments-to-chatter-files <sfdc-convert-attachments-to-chatter-files@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [DouglasCAyers/sfdc-convert-attachments-to-chatter-files] Convert attcehemnt to file tab is always giving setting options (#27) (External Email)

Hi Douglas,

Thanks  for your precious time to giving into my issue

There is one problem with this app, actually while converting  attachment into file for each attachment it is creating  of attachment and file ,means it is creating duplicate attachments. For example we have 2 attachments in case record when we click on conversion it creating duplicate 2 attachments along with files so  total 4 attachments and 2 files.is there any way to change the setting somewhere either in conversion setting or somewhere to only create the file not the attachments.

Thanks
Rajni

**Comment by rbhagat30** [comment]
How we can convert already existing  attachments into files. i am trying to convert all the attachments for case object ,Idid conversion and automation settings but it is not working.

From: Bhagat, Rajni
Sent: Thursday, July 06, 2017 11:06 PM
To: 'DouglasCAyers/sfdc-convert-attachments-to-chatter-files' <reply@reply.github.com>; 'DouglasCAyers/sfdc-convert-attachments-to-chatter-files' <sfdc-convert-attachments-to-chatter-files@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [DouglasCAyers/sfdc-convert-attachments-to-chatter-files] Convert attcehemnt to file tab is always giving setting options (#27) (External Email)

Hi Douglas,
 I have done all the setting  this is not working  still not working for me .
Please find the screenshot

[cid:image001.png@01D2F6B2.3BE34F50]

From: Bhagat, Rajni
Sent: Monday, July 03, 2017 11:30 AM
To: DouglasCAyers/sfdc-convert-attachments-to-chatter-files <reply@reply.github.com>; DouglasCAyers/sfdc-convert-attachments-to-chatter-files <sfdc-convert-attachments-to-chatter-files@noreply.github.com<mailto:sfdc-convert-attachments-to-chatter-files@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [DouglasCAyers/sfdc-convert-attachments-to-chatter-files] Convert attcehemnt to file tab is always giving setting options (#27) (External Email)

Hi Douglas,

Thanks  for your precious time to giving into my issue

There is one problem with this app, actually while converting  attachment into file for each attachment it is creating  of attachment and file ,means it is creating duplicate attachments. For example we have 2 attachments in case record when we click on conversion it creating duplicate 2 attachments along with files so  total 4 attachments and 2 files.is there any way to change the setting somewhere either in conversion setting or somewhere to only create the file not the attachments.

Thanks
Rajni

**Comment by DouglasCAyers** [comment]
Hi @rbhagat30,

Sorry to hear you're still having issues. I know you've tried to send screen shots, but GitHub does not support images from email replies. Please try pasting the images as new comments to this issue from the GitHub website directly.

A couple troubleshooting items:

1. Please confirm you have the latest managed package version installed from the [Package History](https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files#packaged-release-history) links on the README. As of this comment, the latest version is 1.1

2. Please confirm that after installing the managed package that you assign yourself the permission set **Convert Attachments to Files**

3. Please confirm that your Salesforce user is a System Administrator with "Modify All Data" permission.

Thanks,

Doug

**Comment by rbhagat30** [comment]
Hi Douglas,


Thanks for reply .

Below all the 3 points are correct in my case but still it is not working for existing attachments.

Thanks
Rajni

**Comment by rbhagat30** [comment]
![image](https://user-images.githubusercontent.com/29428190/28006963-3521161c-656f-11e7-8e2f-a046b4322a5f.png)

**Comment by rbhagat30** [comment]
![image](https://user-images.githubusercontent.com/29428190/28007013-668e3680-656f-11e7-9b9e-08ed58db14b8.png)

**Comment by rbhagat30** [comment]
![image](https://user-images.githubusercontent.com/29428190/28007050-8bd09712-656f-11e7-9eb0-73a5cf148118.png)

**Comment by rbhagat30** [comment]
![image](https://user-images.githubusercontent.com/29428190/28007144-dd07afc6-656f-11e7-9215-4a7517a11b20.png)

**Comment by rbhagat30** [comment]
![image](https://user-images.githubusercontent.com/29428190/28007221-2cdc7900-6570-11e7-9066-d1b6b8427535.png)

**Comment by rbhagat30** [comment]
Hi Douglas,

i dont have veiw all and modify all data permission for my system admin  profile  is that the reason it is not converting my existing attachments.

If this is the case than why it is working for new attachments?

Thanks in advance 
Rajni

**Comment by DouglasCAyers** [comment]
Hi @rbhagat30,

Thanks for the screen shots. When you are on the **Main Menu > Test Conversion** page per [this comment](https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files/issues/27#issuecomment-314027286), when you click the **Submit** button, what shows up in **Setup | Jobs | Apex Jobs**?

Do any `Convert_Attachments_to_Files_Log__c` records get created?

Thanks

**Comment by rbhagat30** [comment]
Hi Douglas,

I can not see any records in  Convert_Attachments_to_Files_Log__c. The job is submitted from apex jobs.

I don’t have modify all and view all data permission for my system admin profile.

Thanks
Rajni

**Comment by rbhagat30** [comment]
I am getting Apex script unhandled exception by user/organization: 00532000006BvL7/00D0n0000000OLW Source organization: 00D3000000008KK (null) Failed to process batch for class 'dca_cnvrt_file.ConvertAttachmentsToFilesBatchable' for job id '7070n000002AyXv'

caused by: System.LimitException: Too many SOQL queries: 201
 error

**Comment by rbhagat30** [comment]
can i schedule a job for already existing attachment ,in auto conversion setting i didn't find the any option to schedule a job for already  existing attachment .

**Comment by rbhagat30** [comment]
hOW CAN I DEAL WITH BELOW ERROR

**Comment by rbhagat30** [comment]
even if i run the single record same error is coming

**Comment by DouglasCAyers** [comment]
Hi @rbhagat30,

Thanks for the follow up and glad you found the error:
> Too many SOQL queries: 201

My guess is that (a) your org might have triggers on `ContentVersion`, `ContentDocument`, and/or `ContentDocumentLink` objects that are interferring with the conversion. Also, if there are any **after delete** Attachment triggers then that may interfere also by adding to the number of SOQL calls.

See if you can disable any other triggers that might exist and/or reduce the **Batch Size** on the **Test Conversion** menu, specifying a single parent record id that has exactly one attachment and see if you can get a simple test to work.

**Comment by DouglasCAyers** [comment]
If you need to bring some sanity back into your life, you can install the managed package into a new developer org just to prove to yourself the app does work ;)

**Comment by rbhagat30** [comment]
Yes Douglas you are correct.It is working fine in dev sandbox.

**Comment by rbhagat30** [comment]
Hi Douglas ,

Thankyou so much for your help .Again i am facing some difficulty ,it will be really great if you can help me in this.
App is working perfect in dev .but when i test in test sand box it is throghing "First error: ContentPublication Limit exceeded." error. i tried to run the job with all combination still it is not working for me . yes we have  content version trigger in our org, but now confusion here is it is also there in dev sandbox and it is activated. in test sandbox it is throwing error for single record also. i tried to reduce the batch size also but it didnt worked.
please help me  in this.
![job](https://user-images.githubusercontent.com/29428190/28069222-51e55ed2-6666-11e7-8ecf-585b2f079296.png)

**Comment by DouglasCAyers** [comment]
Yes, there is a limit to max files that can be published in 24 hours. Historically this has been 36,000 but Summer 17 release [increased it to 200,000](https://releasenotes.docs.salesforce.com/en-us/summer17/release-notes/rn_files_limits.htm).

You may need to contact Salesforce Support to ensure the limit has been increased in your orgs. 

It's on my todo list to add feature to this app to set our own limits to try and stay within daily governor limit. 

Please see [FAQ](https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files/blob/master/README.md#faq) as that may answer some other questions.

**Comment by rbhagat30** [comment]
Hi douglas ,

i am trying to execute only for 2000 records(as per this ;-Yes, there is a limit to max files that can be published in 24 hours. Historically this has been 36,000 but Summer 17 release increased it to 200,000.)

still i am getting some errors in this:-First error: Too many SOQL queries: 201(do we have to disable the triger) if we can not disable the triger thenn what will be possible solutions.

**Comment by DouglasCAyers** [comment]
Please do disable any other triggers the org may have active for ContentDocument, ContentVersion, ContentDocumentLink, and Attachment. 

You also may need to test with smaller batch size until the SOQL limit exception decreases.
