### ISSUE TITLE
Already existing attachment are not coverting

### ISSUE THREAD

**Issue by rbhagat30** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#28]
I am trying to convert attachment into files through this app,but this app is only convert into files only when new attachment is uploaded.what about already existing attachment, will it not work for a alreday existing attachment .or i  missed something.
![untitled1](https://user-images.githubusercontent.com/29428190/27952843-603afdbc-6327-11e7-9259-a787a53b68c5.png)

**Comment by DouglasCAyers** [comment]
Hi @rbhagat30,

To convert existing Attachments you need to navigate to the *Convert Attachments to Files* tab and choose menu *2. Test Conversion*.

On that page you can specify either one or more comma-delimited parent record ids whose attachments to convert *or* leave that textarea blank to convert all existing attachments.

![image](https://user-images.githubusercontent.com/4142577/27990742-82ee8f7c-6426-11e7-92ae-c7905298a9ac.png)

![image](https://user-images.githubusercontent.com/4142577/27990745-85bdf670-6426-11e7-8f01-d8430a1e92d7.png)

**Comment by rbhagat30** [comment]
Hi Doug,

I want to convert  it for all case attachment . Attachment Parent Record IDs (comma-separated)  field I kept it blank.

Stil it is not converting existing attachment.

Thanks
Rajni
