### ISSUE TITLE
Not all Attachment converted

### ISSUE THREAD

**Issue by rbhagat30** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#30]
We have around 300k attachments we have run the job for all records and job completed successfully  but some attachment are not converted into files .is there any criteria why it is not working . 
is there a way to find those record which are not converted and if we can run the record again.why it is not working ..we might loos the data we can't do the testing for all 300k records.

quick help will really helpfull .

Thanks in advance

**Comment by rbhagat30** [comment]
Could you please help me in this

**Comment by DouglasCAyers** [comment]
Hi @rbhagat30,

Are any errors being reported in the Convert Attachments to Files Log object?

In my next release I'm addressing reportability of which records did and didn't get converted (and why). I can't give a definite ETA when that'll happen, but it's in the develop branch at the moment on github.

**Comment by rbhagat30** [comment]
Hi Douglas,

I can not see any error ,that’s why  I am not able to find it out ☹

Please let me know if you have alternate way to do this.

Thanks
Rajni

**Comment by DouglasCAyers** [comment]
Without any errors or log files to trace back an issue to, I'm not really sure how to help.

You might try Salesforce's own attachment conversion tool they made available in Summer '17 release: https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000EHAmyUAH

Sorry I couldn't be of more help on this issue
