### ISSUE TITLE
Attachemnet to file conversion is not working for some records

### ISSUE THREAD

**Issue by rbhagat30** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#31]
Hi douglas ,

Could you please help me in this why all attachmnets are not converted. i run the job  again for those record which was not converted . but still it is not working. is there a limit for particular org .. our org limit is already 200k for 24 hr.but here i am not able to figure it  out why  it is not working for some of the records. some attachments are not converted ..if i missed something then it should not convert all attachments .

Please help ! 
Its really Urgent.

Thanks

**Comment by DouglasCAyers** [comment]
Duplicate https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files/issues/30
