### ISSUE TITLE
Question: Also sharing with the Parent Account

### ISSUE THREAD

**Issue by amessineo** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#33]
One of the main complaints I have received from users since moving from Attachments to Files is that when on the parent account record, you can no longer see the files for child objects like Cases and Opportunities.
I am wondering if you have come across this also, and if there is a solution to mass share up to the parent account as well.

Thanks!
Anne-Marie

**Comment by DouglasCAyers** [comment]
Hi @amessineo,

That is a common complaint. Files do not roll up to parent Account like Attachments do, unfortunately. That related list is driven completely by which files are explicitly shared to it and not via inferred relationships.

Per this [help article](https://help.salesforce.com/articleView?id=000231874&type=1), it is working as designed.

With that said, that doesn't mean you can't have your own automation or triggers in place on `ContentDocumentLink` that when a file is shared to certain entities (e.g. Contact and Opportunity) to then share or unshare them with the parent entity (e.g. Account). Hrmm... if someone hasn't done that already, sounds like a good hobby project =)

**Comment by DouglasCAyers** [comment]
Hi @amessineo, just FYI, I'm working on this feature but it'll be part of this new project: https://github.com/DouglasCAyers/sfdc-child-files-lightning

Thanks!
