### ISSUE TITLE
Large size attachemnet files are not converting

### ISSUE THREAD

**Issue by rbhagat30** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#36]
Hi douglas,

I observed that the app is not able to convert large  (more that 200 mb may be ) attachments into files is there any workaround .did i missed  something from side . i had around 300k attachments i can see all are concerted except 8k record and those record are having large size.

please help if there is any workaround for larger files.

thanks in advance.

**Comment by DouglasCAyers** [comment]
Thanks for the feedback. I'll investigate. 

Can you confirm that your org hasn't reached any storage limits?

**Comment by rbhagat30** [comment]
No we have sufficient storage .i am not wondering  why only  8k are not converted .

**Comment by DouglasCAyers** [comment]
What batch size are you using? The default I believe is **100**. Try with a smaller number like 50 and keep reducing (25 .. 10 .. 5 .. 1) until get to a number that can convert the batch without exceeding Heap Limit.

Thanks

**Comment by rbhagat30** [comment]
Yes dauglas I tried for 1 also but bad luck not working ☺

**Comment by DouglasCAyers** [comment]
How big are these Attachments that you have left to convert? I'm pretty surprised that even with batch size 1 that it fails to convert one Attachment.

**Comment by rbhagat30** [comment]
Size is different for each attachment it is 50 -300 kb. So we cant say it is attachment size issue.

**Comment by DouglasCAyers** [comment]
Good to know, thanks @rbhagat30. If the heap size limit is not being exceeded by a single attachment when batch size is 1 then it might be related to how the code is querying for and determining if a record has already been converted. Perhaps exceeding memory size simply due to volume of records queried. I'll see what I can uncover.

**Comment by rbhagat30** [comment]
Thanks for the reply douglas I  am sure that record is not converted into files .

**Comment by rbhagat30** [comment]
[cid:image001.png@01D320BD.A420FF10]
[cid:image002.png@01D320BD.AAF3AB80]

**Comment by JPWallhorn** [comment]
Hey Doug,

do I change the batch size under 2. Convert Attachments to Files --> Does the batch size apply to the scheduled job? 

Thank you

**Comment by rbhagat30** [comment]
Hello Douglas,

Did you get chance to look to this one. This is surprising me now even if i am submitting the job for single record still it is not converting after the successfully compilation of the job

**Comment by DouglasCAyers** [comment]
Hi @rbhagat30,

Your [earlier comment](https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files/issues/36#issuecomment-325567236) looked like you might have tried to email reply with images but GitHub doesn't support images from email replies.

Would you mind making a new comment from the [website](https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files/issues/36) and post the images?

Thanks,

Doug

**Comment by DouglasCAyers** [comment]
Are there any other apex triggers on Attachment, ContentVersion, ContentDocument, or ContentDocumentLink objects in your org? Maybe other code is running that might be affecting the heap size?

**Comment by DouglasCAyers** [comment]
Have we confirmed you are using the latest release 1.2 of the managed package?

**Comment by DouglasCAyers** [comment]
Last spammy comment reply of the night, please run this SOQL query in your org and let me know the results. I wonder if a single record might have a large quantity of related attachments perhaps?

`SELECT count(id), parent.type FROM Attachment GROUP BY parent.type ORDER BY count(id)`

Thanks

**Comment by DouglasCAyers** [comment]
Hi @rbhagat30, I've not been able to reproduce the issue. Let me know if you're still encountering this and if you could provide follow up answers to earlier questions to help troubleshoot.
