### ISSUE TITLE
Only partial conversion in Sandbox environments

### ISSUE THREAD

**Issue by JamesSinor** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#39]
Hi Doug! I am testing your app out in both a full and partial sandbox environment. In both cases, only a subset of the attachments existing in those environments are being converted (5k out of 47k in the full sandbox). Are there common issues that may be leading to this? Our attachments are primarily images and PDFs.

**Comment by DouglasCAyers** [comment]
Hi James,

Can you confirm what parent object those attachments belong to?

In Developer Console you can run this query:
```
SELECT
  parent.type,
  count(id),
  sum(bodyLength)
FROM
  Attachment
GROUP BY
  parent.type
```

The app explicitly [ignores](https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files#are-there-any-objects-that-dont-support-attachment-conversion) any attachments related to **Emails** or **Solutions** as they don't support Files (or we get nasty errors when trying to save Files to them).

Thanks,

Doug

**Comment by DouglasCAyers** [comment]
Another troubleshooting question, can you confirm if the batch job is still running or if it perhaps got aborted or is hung? You can check in Setup | Jobs | Apex Jobs. When you submitted the conversion job in Step 2 you should have received an **Apex Job ID** in a green notification that you can cross-reference with on the Apex Jobs page.

Another thing to check is **data storage**. If your sandbox exceeds the max allowed storage thresholds it might prevent you from creating new data and the job may have aborted then.

**Comment by JamesSinor** [comment]
Hi Doug,

It looks like this error is coming up frequently for me: "ContentPublication Limit exceeded." I see documentation that developer and trial editions can publish a maximum of 2,500 new versions in a 24 hour period. Does this limit also apply to sandbox environments and is that likely the source of the error? We're at exactly 5,000 files converted after submitting the job over two days, so the numbers line up there.

No relevant jobs are queued/processing/preparing/holding right now. We are at 69% storage for data and 11% storage for files. 

Here is the file breakdown for our full sandbox environment (I was way off in the numbers I got using data loader...need to work on my attachment export skills apparently!). Most of our attachments live on the Opportunity and Product2 objects.

APXTConga4__Conga_Template_c: 437 (count), 61750192 (sum)
Account, 1123 (count), 417195055 (sum)
Asset, 61 (count), 14778666 (sum)
Campaign, 3 (count), 13459904(sum)
Case, 839 (count), 673210430 (sum)
Contact, 1020 (count), 421718957 (sum)
EmailMessage, 24 (count), 653688 (sum)
Finance_Application__c, 1 (count), 46950 (sum)
Lead, 122 (count), 79879397 (sum)
Opportunity, 12005 (count), 19298374742 (sum)
Product2, 14933 (count), 6750173465 (sum)
Quote, 37 (count), 84324937 (sum)
Solution, 1 (count), 220271 (sum)
Unit__c, 203 (count), 27471234 (sum)
echosign_dev1__SIGN_Agreement__c, 823 (count), 117096033 (sum)
TOTAL: 16245 (count), 9162417700 (sum)

**Comment by DouglasCAyers** [comment]
Thanks for the follow up @JamesSinor. I would definitely reach out to Salesforce Support and ask for the limit to be increased in your sandbox environments. I don't think you'd run into any push back if you explain that you're trying to adopt new features but need to sanity check the data conversion first. If you do get push back, let me know.

**Comment by JamesSinor** [comment]
Perfect. Will do!

**Comment by JamesSinor** [comment]
Thank you, Doug! That solved the issue. Apparently this sandbox was last refreshed prior to Salesforce increasing the number of Content Versions that can be published per day. Here is the knowledge article on those limits for different environments:

https://help.salesforce.com/articleView?id=Increasing-the-Max-number-of-Content-Versions-published-per-day&language=en_US&type=1

**Comment by DouglasCAyers** [comment]
Good to know, thanks for follow up!
