### ISSUE TITLE
Prevent conversion to attachments on certain objects

### ISSUE THREAD

**Issue by CurGeorge8** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#40]
We are currently using Salesforce Quote to Cash (A.K.A.  Salesforce CPQ, A.K.A. Steelbrick CPQ). This will generated a quote pdf and save it as an attachment on the SBQQ__RecordJob__c object.

For both the auto conversion process and CPQ to live in the same world, I need to prevent the auto conversion trigger from firing on any records related to any custom objects with the SBQQ__ prefix.

**Comment by DouglasCAyers** [comment]
Hi @CurGeorge8, I hear you loud and clear on this one and it's one that I've been wanting to implement for a while. Please follow this issue for progress updates https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files/issues/15

I'll be closing this specific issue but tracking the request on the other issue.

Thanks!
