### ISSUE TITLE
Errors when trying to install the code to a production/developer's org

### ISSUE THREAD

**Issue by jmendez990** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#41]
Hi Douglas,

I hope your are doing fine so far. I am trying to install you app for converting attachment to files, since it tried installing the one from salesforce labs and it does not let me install it. When I try to install yours into my org, it display the following errors:

This app can't be installed.
There are problems that prevent this package from being installed.

Dependent class is invalid and needs recompilation: Class dca_cnvrt_file.ConvertAttachmentsToFilesBatchable : Dependent class is invalid and needs recompilation: Class dca_cnvrt_file.ConvertAttachmentsToFilesService : Field is not writeable: ContentVersion.CreatedById | ConvertAttachmentsRunOnceController: Dependent class is invalid and needs recompilation: Class dca_cnvrt_file.ConvertAttachmentsToFilesBatchable : Dependent class is invalid and needs recompilation: Class dca_cnvrt_file.ConvertAttachmentsToFilesService : Field is not writeable: ContentVersion.CreatedById.

I thank you before hand for any help you can provide me regarding this matter.

**Comment by DouglasCAyers** [comment]
Hello, thanks for trying my migration app out!

For either app to install you will need to enable Create Audit Fields and grant permission to your profile. 

https://help.salesforce.com/articleView?id=000213290&type=1&language=en_US
