### ISSUE TITLE
Can we exclude a record type?

### ISSUE THREAD

**Issue by DarylMoon** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#47]
Hi Doug, we have a legacy app that allows clients to upload documents (as attachments) to opportunities via a portal. Apparently these anonymous portal users do not have access to Salesforce files (only attachments) so we need to exclude these attachments from being converted (for a couple of opportunity record types).  Can the object selection be expanded to add a number of record types to be excluded from the automated (batch) conversion process?

**Comment by DouglasCAyers** [comment]
Hi @DarylMoon, I hear you loud and clear on this one and it's one that I've been wanting to implement for a while. Please follow this issue for progress updates #15

I'll be closing this specific issue but tracking the request on the other issue.

Thanks!
