### ISSUE TITLE
Nothing happens when I press convert

### ISSUE THREAD

**Issue by SarahLambertson** [douglascayers/sfdc-convert-attachments-to-chatter-files#51]
When I submit a conversion, I get a green bar at the top of the screen saying "Conversion batch job submitted:  7072100000SSy4kAAD", but nothing happens. When I got to the Convert Attachments to Files logs there is nothing there. No errors and nothing converted. I'm not receiving errors anywhere, but nothing seems to be happening. I'm working in a partial sandbox.

**Comment by douglascayers** [comment]
Hi @SarahLambertson,

In Setup, do you see the job listed under **Apex Jobs** page?

![image](https://user-images.githubusercontent.com/4142577/40880070-20e5e17a-6670-11e8-8ac8-c15a3ee8f295.png)

**Comment by srihithacherukuri** [comment]
I also have the same error when I try converting using the single parent ID as well it isn't working and I have attached the screenshot of the apex jobs 
![error](https://user-images.githubusercontent.com/43141223/45762244-f10ac380-bbfb-11e8-9e62-d323b15e4116.PNG)

**Comment by shaunybegoode** [comment]
I have the same problem.  If I add a sinle record ID then it processes fine.  If I add a second (comma separated) the job stays as 'processing'.  If I try to add none it also stays as processing.  

It has worked in a dev sandbox but hits this problem in a partial copy sandbox.  

I saw there were problems in the past with PC sandboxes and files but it does not seem to be an exact match here as I can create and view files, and those that are converted on their own are visible. 

I have tried dropping batch size but no change.

Using v1.3 in an EE org where 0% of file storage is used (but total number of attachments is about 1700 so small volume)

I have set debugging and no limits appear to be hit, am not sure if the following is of use, its the last line of the debugs:

```
16:00:29.0 (100196856)|SOQL_EXECUTE_BEGIN|[245]|Aggregations:0|SELECT contentDocument.latestPublishedVersionId, contentDocument.latestPublishedVersion.original_record_id__c FROM ContentDocumentLink 
16:00:29.0 (120755665)|SOQL_EXECUTE_END|[245]|Rows:0
16:00:29.0 (153304514)|SAVEPOINT_SET|[141]|SavepointValue2
16:00:29.0 (154133853)|DML_BEGIN|[148]|Op:Insert|Type:ContentVersion|Rows:100
16:00:29.0 (331689484)|DML_END|[148]
```

**Comment by douglascayers** [comment]
Thanks @shaunybegoode for the update on issue being with un-copied records in a *Partial Copy Sandbox*.

@SarahLambertson @srihithacherukuri can you confirm if you had this issue in Partial Copy Sandboxes too?

**Comment by SarahLambertson** [comment]
I was also in a partial copy sandbox, so that seems consistent for me.

**Comment by srihithacherukuri** [comment]
I am facing issues in the partial sandbox

**Comment by douglascayers** [comment]
Thanks for the confirmation. Mystery solved
